---
version: 13.0.0
slug: samba
name: Samba share
description: Expose Home Assistant folders with SMB/CIFS
url: https://github.com/home-assistant/addons/tree/master/samba
# codenotary: notary@home-assistant.io
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
hassio_api: true
host_network: true
# image: homeassistant/{arch}-addon-samba
init: false
map:
  - addons:rw
  - all_addon_configs:rw
  - backup:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl:rw
options:
  workgroup: WORKGROUP
  compatibility_mode: false
  veto_files:
    - ._*
    - .DS_Store
    - Thumbs.db
    - icon?
    - .Trashes
  allow_hosts:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    - 169.254.0.0/16
    - fe80::/10
    - fc00::/7
  users:
    - username: homeassistant
      password: null
  shares:
    - share_name: config
      path: /homeassistant
      deny: []
    - share_name: addons
      path: /addons
      deny: []
    - share_name: addon_configs
      path: /addon_configs
      deny: []
    - share_name: ssl
      path: /ssl
      deny: []
    - share_name: share
      path: /share
      deny: []
    - share_name: backup
      path: /backup
      deny: []
    - share_name: media
      path: /media
      deny: []


schema:
  workgroup: str
  compatibility_mode: bool
  veto_files:
    - str
  allow_hosts:
    - str
  users:
    - username: str
      password: password
  shares:
    - path: "match(^(?:\\/\\w+)+$)"
      share_name: "match(^\\w+$)"
      deny:
        - str
startup: services
